### PR TITLE
Improve drawing trade routes on map

### PR DESCRIPTION
**Pull request by Slornie**
Contributes to #57.

- After right-clicking a planet on the plot and activating the "draw trade route" function:
  - A trace line is drawn from that planet to the cursor
  - ~~A crosshairs is drawn around the cursor~~ (Removed)
- These remain active until the "drawn" trade route is completed (by right clicking on another planet) or cancelled (by right clicking on the starting planet).

- Right clicking on the same planet twice in a row now cancels the "draw trade route" (as mentioned above) rather than launching the "new trade route" dialog with the same start and end locations.
- The "new trade route" dialog from the menu bar has **NOT** been updated and may still permit routes to be created with the same start and end locations.

image

### CODE REVIEW

**Comment by andrewfullard** [comment]
I don't think the line drawing is entirely necessary, certainly the crosshair seems overkill to me. The other changes are good though.

**Comment by Slornie** [comment]
I think there needs to be some form of visual cue to the user that they've clicked to start a trade route.  Otherwise you can easily forget and click elsewhere only to find you've unintentionally drawn a route across the map.  The line drawing serves that purpose but also makes it easier to visualise the line(s) while planning the GC.

I've dropped the crosshairs though; that was mainly there because it was the first thing I got working and I didn't want to take it out right away!

**Comment by andrewfullard** [comment]
Okay, resolve that conflict and we can merge

**Comment by Slornie** [comment]
Fixed!

**Pull request merged**
